### ISSUE TITLE
질문) 질문입니다.

### ISSUE THREAD

**Issue by hooong** [junstone1995/programmers#1]
https://github.com/junstone1995/programmers/blob/e83b4f28ba1b6e6be6582c209d08a35cb63f0d87/Level1/%EC%A0%95%EC%88%98%20%EC%A0%9C%EA%B3%B1%EA%B7%BC%20%ED%8C%90%EB%B3%84.swift#L5

swift의 sqrt()는 파라미터로 int가 들어가면 반환값이 int인가요?? 반환값이 double라면 n을 구지 double로 바꾼 이유가 궁금하네요❓

**Comment by junstone1995** [comment]
swift의 sqrt()함수는 double 형만 받을 수 있습니다. 
sqrt(double) -> double

**Comment by hooong** [comment]
LGTM!
